### ISSUE TITLE
Домашка №1, HTML

### ISSUE THREAD

**Issue by tiny-kottan** [stasgavrylov/kottans#2]
Разметить эту страницу: https://habrahabr.ru/post/244929/
от вас ожидаеться `.html` файл с семантичной разметкой, без css/js
крупные части контента копипастить не стоит (саму статью, там `h*`/`p`/`code` -- все просто), а вот остальное -- нужно
как должно выглядить
```html
<!doctype html>
<html lang=ru>
<meta charset=utf-8>
<title>Habrahabr.ru</title>
<header>
  <ul>
    <li><a href=...>TM Feed</a>
    <li><a>Хабрахабр</a>
  </ul>```

**Comment by stasgavrylov** [comment]
https://github.com/stasgavrylov/kottans/tree/master/hw1

**Comment by mkozhukharenko** [comment]
https://github.com/stasgavrylov/kottans/blob/master/hw1/index.html#L10-L37
you don't need those navs
read [this](http://html5doctor.com/avoiding-common-html5-mistakes/#nav-external) to find out how to use this element properly

**Comment by mkozhukharenko** [comment]
same issue https://github.com/stasgavrylov/kottans/blob/master/hw1/index.html#L64-L81

**Comment by mkozhukharenko** [comment]
can be an article https://github.com/stasgavrylov/kottans/blob/master/hw1/index.html#L179-L195

**Comment by mkozhukharenko** [comment]
I wouldn't use a an `address` here https://github.com/stasgavrylov/kottans/blob/master/hw1/index.html#L276-L287

**Comment by mkozhukharenko** [comment]
Why didn't you wrap a main article in an `article` element? https://github.com/stasgavrylov/kottans/blob/master/hw1/index.html#L221-L258

**Comment by mkozhukharenko** [comment]
you don't need a form here https://github.com/stasgavrylov/kottans/blob/master/hw1/index.html#L263

**Comment by stasgavrylov** [comment]
@mkozhukharenko 
1. I agree that the content in `<address>` is not appropriate in this case. To be honest, I didn't notice that there're sharing links, and decided that they may point to authors contacts in social networks.
2. I agree that main article should've been wrapped in `<article>` element. In that case, I just forgot about this.
3. I didn't find any strict rules about `<form>` element. I decided that this would not be inappropriate, because in general it's implied, that the result of interaction with these controls will be sent to the server.
4. As for `<nav>` element, I believe that this is really arguable. I mean, all semantics topic in general is opinionated, and as long as it's not a `<div>` soup, different markup options can be viable. I believe that blocks of links that point to external resources should be considered "major navigation blocks". Because there's really no strict definition of such blocks. Here's an [article](http://html5doctor.com/nav-element/) from the same resource, that you've mentioned, which brings several points that are almost completely contrary to yours. Which, imho, only  confirms, that there's no "black and white" here.

Thanks for your feedback!

**Comment by mkozhukharenko** [comment]
> I didn't find any strict rules about <form> element.

oh, you should read the specification more carefully. [It](https://html.spec.whatwg.org/multipage/forms.html#the-form-element) determines:

> The form element represents a collection of form-associated elements, some of which can represent editable values that can be submitted to a server for processing.

[Form-associated elements ](https://html.spec.whatwg.org/multipage/forms.html#form-associated-element)are:

- button
- fieldset
- input
- keygen
- objecto
- utput
- select
- textarea
- img

you have non of them in you `form` element

**Comment by mkozhukharenko** [comment]
> As for <nav> element, I believe that this is really arguable. 

Can't agree more. It's good that you did a research and arrived to own opinion on that question. 👍
